# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build container
        run: echo Hello, world!

          
  tests:
     runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        # Runs a single command using the runners shell
        - name: Run UnitTest
          run: |
            chmod +x ./gradlew
            ./gradlew testDebugUnitTest
  gradlew_build:
     runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        # Runs a single command using the runners shell
        - name: Build
          run: |
            chmod +x ./gradlew
            ./gradlew build
            ls
        - name: Upload binaries to release
          uses: solovey/upload-release-action@v2
          with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: app/build/outputs/apk/debug/app-debug.apk
              asset_name: solovey
              tag: ${{ github.ref }}
              overwrite: true
              body: "This is my release text"
            
  
