# This is a basic workflow to help you get started with Actions

name: CI test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
       
  tests:
     runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
      - name: Step 1
        id: step1
        run: echo "::set-output name=VAR1::$(head -1 ./versions.txt)"

      - name: emit env
        run: |
          echo $VAR1
        
        env:
          VAR1: ${{ steps.step1.outputs.VAR1 }}

      - name: this should not run
        run: echo "This should not run"
        if: steps.step1.outputs.VAR1 == 'Lucy'
  
